### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by shmuelie**

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks :)

**Comment by SamuelEnglard** [comment]
Did you even check my work? :)

**Comment by madskristensen** [comment]
Briefly. Looks interesting. I'll go through it in more detail later

**Comment by SamuelEnglard** [comment]
Can't wait :)

**Comment by madskristensen** [comment]
@SamuelEnglard It's awesome!!! Thanks so much. I just added VS2017 support as well. Try out the [CI build](http://vsixgallery.com/extension/0798393f-f7b0-4283-a36e-c57a73f031c4/)

**Pull request merged**
